In [1]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load data
df = pd.read_csv('D:/churn/data.csv')

# Show first 5 rows of data (sample data)
print("Sample data:")
print(df.head())

# Check data shape and columns info
print("\nData shape (rows, columns):", df.shape)
print("\nColumns and types:")
print(df.info())

# Check for missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# View descriptive statistics (numeric columns)
print("\nDescriptive statistics:")
print(df.describe())

# Check for duplicate rows
duplicates = df.duplicated().sum()
print(f"\nDuplicate rows count: {duplicates}")

# If duplicates exist, you can drop them:
if duplicates > 0:
    df = df.drop_duplicates()
    print("Duplicates removed.")

print(df.isnull().sum())

Sample data:
   CustomerID  Count        Country       State         City  Zip Code  \
0  3668-QPYBK      1  United States  California  Los Angeles     90003
1  9237-HQITU      1  United States  California  Los Angeles     90005
2  9305-CDSKC      1  United States  California  Los Angeles     90006
3  7892-POOKP      1  United States  California  Los Angeles     90010
4  0280-XJGEX      1  United States  California  Los Angeles     90015

                 Lat Long   Latitude   Longitude  Gender  ...        Contract  \
0  33.964131, -118.272783  33.964131 -118.272783    Male  ...  Month-to-month
1   34.059281, -118.30742  34.059281 -118.307420  Female  ...  Month-to-month
2  34.048013, -118.293953  34.048013 -118.293953  Female  ...  Month-to-month
3  34.062125, -118.315709  34.062125 -118.315709  Female  ...  Month-to-month
4  34.039224, -118.266293  34.039224 -118.266293    Male  ...  Month-to-month

  Paperless Billing             Payment Method  Monthly Charges Total Charges  \
0               Yes               Mailed check            53.85        108.15
1               Yes           Electronic check            70.70        151.65
2               Yes           Electronic check            99.65         820.5
3               Yes           Electronic check           104.80       3046.05
4               Yes  Bank transfer (automatic)           103.70        5036.3

  Churn Label Churn Value Churn Score  CLTV                   Churn Reason
0         Yes           1          86  3239   Competitor made better offer
1         Yes           1          67  2701                          Moved
2         Yes           1          86  5372                          Moved
3         Yes           1          84  5003                          Moved
4         Yes           1          89  5340  Competitor had better devices

[5 rows x 33 columns]

Data shape (rows, columns): (7043, 33)

Columns and types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB
None

Missing values per column:
CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

Descriptive statistics:
        Count      Zip Code     Latitude    Longitude  Tenure Months  \
count  7043.0   7043.000000  7043.000000  7043.000000    7043.000000
mean      1.0  93521.964646    36.282441  -119.798880      32.371149
std       0.0   1865.794555     2.455723     2.157889      24.559481
min       1.0  90001.000000    32.555828  -124.301372       0.000000
25%       1.0  92102.000000    34.030915  -121.815412       9.000000
50%       1.0  93552.000000    36.391777  -119.730885      29.000000
75%       1.0  95351.000000    38.224869  -118.043237      55.000000
max       1.0  96161.000000    41.962127  -114.192901      72.000000

       Monthly Charges  Churn Value  Churn Score         CLTV
count      7043.000000  7043.000000  7043.000000  7043.000000
mean         64.761692     0.265370    58.699418  4400.295755
std          30.090047     0.441561    21.525131  1183.057152
min          18.250000     0.000000     5.000000  2003.000000
25%          35.500000     0.000000    40.000000  3469.000000
50%          70.350000     0.000000    61.000000  4527.000000
75%          89.850000     1.000000    75.000000  5380.500000
max         118.750000     1.000000   100.000000  6500.000000

Duplicate rows count: 0
CustomerID              0
Count                   0
Country                 0
State                   0
City                    0
Zip Code                0
Lat Long                0
Latitude                0
Longitude               0
Gender                  0
Senior Citizen          0
Partner                 0
Dependents              0
Tenure Months           0
Phone Service           0
Multiple Lines          0
Internet Service        0
Online Security         0
Online Backup           0
Device Protection       0
Tech Support            0
Streaming TV            0
Streaming Movies        0
Contract                0
Paperless Billing       0
Payment Method          0
Monthly Charges         0
Total Charges           0
Churn Label             0
Churn Value             0
Churn Score             0
CLTV                    0
Churn Reason         5174
dtype: int64

In [2]:
df = pd.read_csv('D:/churn/data.csv')

# Replace spaces in column names with underscore
df.columns = df.columns.str.replace(' ', '_')

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip_Code           7043 non-null   int64
 6   Lat_Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior_Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure_Months      7043 non-null   int64
 14  Phone_Service      7043 non-null   object
 15  Multiple_Lines     7043 non-null   object
 16  Internet_Service   7043 non-null   object
 17  Online_Security    7043 non-null   object
 18  Online_Backup      7043 non-null   object
 19  Device_Protection  7043 non-null   object
 20  Tech_Support       7043 non-null   object
 21  Streaming_TV       7043 non-null   object
 22  Streaming_Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless_Billing  7043 non-null   object
 25  Payment_Method     7043 non-null   object
 26  Monthly_Charges    7043 non-null   float64
 27  Total_Charges      7043 non-null   object
 28  Churn_Label        7043 non-null   object
 29  Churn_Value        7043 non-null   int64
 30  Churn_Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn_Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB
None

In [3]:
# Convert to numeric
df['Total_Charges'] = pd.to_numeric(df['Total_Charges'], errors='coerce')

# Calculate mean
mean_val = df['Total_Charges'].mean()

# Fill NaN without inplace to avoid warning
df['Total_Charges'] = df['Total_Charges'].fillna(mean_val)

# Churn_Reason की null values को "No Information" से replace किया
df['Churn_Reason'] = df['Churn_Reason'].fillna("No Information")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip_Code           7043 non-null   int64
 6   Lat_Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior_Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure_Months      7043 non-null   int64
 14  Phone_Service      7043 non-null   object
 15  Multiple_Lines     7043 non-null   object
 16  Internet_Service   7043 non-null   object
 17  Online_Security    7043 non-null   object
 18  Online_Backup      7043 non-null   object
 19  Device_Protection  7043 non-null   object
 20  Tech_Support       7043 non-null   object
 21  Streaming_TV       7043 non-null   object
 22  Streaming_Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless_Billing  7043 non-null   object
 25  Payment_Method     7043 non-null   object
 26  Monthly_Charges    7043 non-null   float64
 27  Total_Charges      7043 non-null   float64
 28  Churn_Label        7043 non-null   object
 29  Churn_Value        7043 non-null   int64
 30  Churn_Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn_Reason       7043 non-null   object
dtypes: float64(4), int64(6), object(23)
memory usage: 1.8+ MB

In [5]:
df.isnull().sum()

CustomerID           0
Count                0
Country              0
State                0
City                 0
Zip_Code             0
Lat_Long             0
Latitude             0
Longitude            0
Gender               0
Senior_Citizen       0
Partner              0
Dependents           0
Tenure_Months        0
Phone_Service        0
Multiple_Lines       0
Internet_Service     0
Online_Security      0
Online_Backup        0
Device_Protection    0
Tech_Support         0
Streaming_TV         0
Streaming_Movies     0
Contract             0
Paperless_Billing    0
Payment_Method       0
Monthly_Charges      0
Total_Charges        0
Churn_Label          0
Churn_Value          0
Churn_Score          0
CLTV                 0
Churn_Reason         0
dtype: int64

In [8]:
df.to_csv('D:/churn/cleaned_Telco_customer_churn.csv', index=False, encoding='utf-8')